server:
    address: 0.0.0.0
    port: ${PORT:8080}
credential:
  telegram:
    login: ${TG_BOT_NAME:}
    token: ${TG_BOT_TOKEN:}
  youtube:
    key: ${YOUTUBE_API_KEY:}
search:
  youtube:
    maxresults: ${MAX_RESULTS:10}